spring:
#DATABASE(CONNECTING)
  datasource:
    url: jdbc:postgresql://localhost:5432/learn
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

#DATABASE(CONFIGURATION)
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate.ddl-auto: update


  #DATABASE(LIQUIBASE CONFIGURATION)
  liquibase:
    enabled: true
    change-log: classpath*:db/changelog/db.changelog-master.yml

#SPRING SECURITY(BEARER TOKEN)
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m